<h2>Registrace nového člena</h2>
<form method="post" action="" name="registrationForm">
	<table>
		<tr>
			<td class="right">
				<label for="email">Email - bude použit jako login: </label>
			</td>
			<td class="left">
				<input type="email" name="email" id="email" value="<?php if (!empty($email))
					echo($email); ?>" required autocomplete="email">
			</td>
		</tr>
		<tr>
			<td class="right">
				<label for="firstname">Jméno: </label>
			</td>
			<td class="left">
				<input type="text" name="firstname" id="firstname" value="<?php if (!empty($firstname))
					echo($firstname); ?>" required autocomplete="given-name">
			</td>
		</tr>
		<tr>
			<td class="right">
				<label for="surname">Příjmení: </label>
			</td>
			<td class="left">
				<input type="text" name="surname" id="surname" value="<?php if (!empty($surname))
					echo($surname); ?>" required autocomplete="family-name">
			</td>
		</tr>
		<tr>
			<td class="right">
				<label for="telephone">Telefon (volitelně): </label>
			</td>
			<td class="left">
				<input type="tel" name="telephone" id="telephone" value="<?php if (!empty($telephone))
					echo($telephone); ?>" autocomplete="tel">
			</td>
		</tr>
		<tr>
			<td class="right">
				<label for="address">Adresa: </label>
			</td>
			<td class="left">
				<input type="text" name="address" id="address" value="<?php if (!empty($address))
					echo($address); ?>" required>
			</td>
		</tr>
		<tr>
			<td class="right">
				<label for="ic">IČ (volitelně): </label>
			</td>
			<td class="left">
				<input type="text" name="ic" id="ic" value="<?php if (!empty($ic))
					echo($ic); ?>">
			</td>
		</tr>
		<tr>
			<td class="right">
				<label for="company">Firma (volitelně pro fakturaci): </label>
			</td>
			<td class="left">
				<input type="text" name="company" id="company" value="<?php if (!empty($company))
					echo($company); ?>">
			</td>
		</tr>
		<tr>
			<td class="right">
				<label for="tariff">Místo a tarif: </label>
			</td>
			<td class="left">
				<select name="tariff" id="tariff" required>
					<option value="X" selected="selected">Vyber místo a tarif...</option>
					<?php
					foreach ($tariffs as $tariff): ?>
						<option value="<?=$tariff['id_tariff']?>">
							<?=$tariff['name']?>:
							<?=$tariff['tariffCZE']?> za
							<?=$tariff['priceCZK']?> Kč
						</option>
					<?php endforeach ?>
				</select>
			</td>
		</tr>
		<tr>
			<td class="right">
				<label for="startDate">Datum začátku fakturace: </label>
			</td>
			<td class="left">
				<input type="date" id="startDate" name="startDate" value="<?=date('Y-m-d', time());?>">
			</td>
		</tr>
		<tr>
			<td colspan="2" class="center">
				<button type="submit" name="sent"
				        onclick="return regformhash(this.form, this.form.password, this.form.passwordComfirm);">
				Registrovat!</button>
			</td>
		</tr>
	</table>
</form>
