<h2>Nové heslo</h2>
<form method="post" id="restartPassword">
	<table>
		<tr>
			<td>
				<label for="email">Tvůj email použitý při registraci: </label>
			</td>
			<td>
				<input type="email" id="email" name="email" required="required"
					   value="<?php if (isset($_SESSION['username'])) echo($_SESSION['username']) ?>"/><br/>
			</td>
		</tr>
		<tr>
			<td>
				<label for="year">Antispam - zadej loňský rok: </label>
			</td>
			<td>
				<input type="text" id="year" name="year" required="required"><br/>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="submit" name="sent" value="Poslat email s žádostí o nové heslo"/>
			</td>
		</tr>
	</table>
</form>