<h2>Úvod</h2>
<!--<p><a href="http://www.activism.net/cypherpunk/crypto-anarchy.html">Přečti si cryptoanarchistický manifest</a></p>-->
<div class="intro">
	<ul>
		<li><?=NAME?> vyvíjený primárně pro potřeby Paralelní Polis</li>
		<li><?=NAME?> je interní platební systém pro členy Paper Hubu, Institutu Kryptoanarchie a Makers Labu</li>
		<!--<li>Zdrojové kody budou zveřejněny na GitHubu</li>
		<li>Happy hacking, please reporting</li>-->
		<li>Jsi tu poprvé? <a href="<?=ROOT?>/cs/registration">Zde se můžeš zaregistrovat!</a></li>
	</ul>
</div>
