<h2>
	<i><?= $user['first_name'] ?> <?= $user['last_name'] ?></i>
</h2>
<h3>
	s tarifem <?= $user['tariffCZE'] ?> (<?= $tariff['priceCZK'] ?> Kč/měsíc) v <?= $user['name'] ?>
</h3>

<table class="user">
    <tr class="firstRow">
        <td>Datum</td>
        <td>Cena v BTC</td>
        <td>Status faktury</td>
        <td>Zaplatit</td>
        <td>Link na stažení faktury</td>
        <?php if ($admin): ?>
            <td>Rušení faktur</td>
            <?php endif ?>
    </tr>
    <?php foreach ($payments as $p): ?>
        <tr>
            <td>
                <?= date("j/n y", strtotime($p['payment_first_date'])) ?>
                    až
                    <?= date("j/n y", strtotime($p['payment_first_date']."+1 month -1 day")) ?>
            </td>
            <td>
                <?= $p['payed_price_BTC'] * 1000 ?> mBTC
            </td>
            <td>
                <b><?= $p['status'] ?></b>
            </td>
            <td>
                <a href="<?= ROOT ?>/cs/PayInvoice/pay/<?= $p['id_payment'] ?>">
                    <button>Zaplatit</button>
                </a>
            </td>
            <td>
                <a href="<?= ROOT ?>/cs/InvoicePdf/<?= $p['invoice_fakturoid_id'] ?>" target="_blank">
                    <button>ukázat PDF</button>
                </a>
            </td>
            <?php if ($admin): ?>
                <td>
                    <a href="<?= ROOT ?>/cs/DeleteInvoice/<?= $p['id_payment'] ?>">
                        <button>Zrušit fakturu!</button>
                    </a>
                </td>
                <?php endif ?>
        </tr>
        <?php foreach ($p['extras'] as $e): ?>
            <tr>
                <td class="right">
                    <?php if ($admin): ?>
                        <a href="<?= ROOT ?>/cs/extras/delete/<?= $e['id_extra'] ?>">
                            <button>Smazat!</button>
                        </a>
                        <?php endif; ?>
                </td>
                <td>
                    +
                    <?= $e['priceBTC'] * 1000 ?> mBTC
                </td>
                <td colspan="4">
                    <?= $e['description'] ?>
                </td>
            </tr>
            <?php endforeach ?>
                <?php if ($admin): ?>
                    <tr>
                        <td class="right">
                            <label for="price">Cena: </label>
                        </td>
                        <td colspan="5">
                            <form method="POST" action="<?= ROOT ?>/cs/extras/add">
                                <input type="hidden" name="paymentId" value="<?= $p['id_payment'] ?>">
                                <input id="price" name="price" type="number" step="any">
                                <label for="description">Popis: </label>
                                <input id="description" name="description" type="text">
                                <button type="submit">Přidat</button>
                            </form>
                        </td>
                    </tr>
                    <?php endif ?>
                        <?php endforeach ?>
</table>
<p><a href="mailto:<?= EMAIL_HUB_MANAGER ?>">Pro změnu tarifu kontaktuj prosím svého Paper Hub manažera</a></p>
