<h2>Nové heslo</h2>
<form method="POST" name="obnoveni_hesla" action="">
	<table>
		<tr>
			<td><label for="password">Nové heslo (alespoň 6 znaků): </label></td>
			<td><input type="password" name="password" id="password"/></td>
		</tr>
		<tr>
			<td><label for="passwordComfirm">Potvrzení hesla: </label></td>
			<td><input type="password" name="passwordComfirm" id="passwordComfirm"/></td>
		</tr>
		<tr>
			<td></td>
			<td><input type="submit" value="Obnovit heslo" name="sent"
					   onclick="return regformhash(this.form, this.form.password, this.form.passwordComfirm);"/></td>
		</tr>
	</table>
</form>