<h2>Nové heslo</h2>
<form method="POST" name="obnoveni_hesla" action="">
    <table>
        <tr>
            <td class="right">
                <label for="password">Nové heslo (alespoň 6 znaků): </label>
            </td>
            <td class="left">
                <input type="password" name="password" id="password" required autocomplete="new-password">
            </td>
        </tr>
        <tr>
            <td class="right">
                <label for="passwordComfirm">Potvrzení hesla: </label>
            </td>
            <td class="left">
                <input type="password" name="passwordComfirm" id="passwordComfirm" required autocomplete="new-password">
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit" name="sent" onclick="return regformhash(this.form, this.form.password, this.form.passwordComfirm);">Obnovit heslo</button>
            </td>
        </tr>
    </table>
</form>
