version: '3'
services:
  app:
    build: .
    depends_on:
        - db
    ports:
     - 80:80
  db:
    image: mysql/mysql-server:5.7
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: root
    restart: always
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    restart: always