<h2>Přehled členů</h2>
<table class="checkUsers">
	<tr class="firstRow">
		<th>Activation</th>
		<th>Personal data</th>
		<th>Name</th>
		<th>Email</th>
		<th>Place</th>
		<!--<th>First membership</th>-->
		<th>Tariff</th>
	</tr>
	<?php foreach ($members as $m) : ?>
		<tr>
			<td>
				<?php if ($m['active']) { ?>
					<a href="<?=ROOT?>/en/forceDeactivation/<?=$m['id_user']?>/<?=$csrf?>">
						<button>deaktivovat</button>
					</a>
				<?php }
				if (!$m['active']) { ?>
					<a href="<?=ROOT?>/en/forceActivation/<?=$m['id_user']?>">
						<button>Aktivovat!</button>
					</a>
				<?php } ?>
			</td>
			<td>
				<a href="<?=ROOT?>/en/changePersonals/<?=$m['id_user']?>/<?=$csrf?>">
					<button>Change!</button>
				</a>
			</td>
			<td>
				<a href="<?=ROOT?>/en/payments/<?=$m['id_user']?>">
					<?=$m['first_name']?>
					<?=$m['last_name']?>
				</a>
			</td>
			<td>
				<a href="mailto:<?=$m['email']?>"><?=$m['email']?></a>
			</td>
			<td>
				<?=$m['name']?>
			</td>
			<!--<td>
				<?=$m['firstPaymentDate']?>
			</td>-->
			<td>
				<div class="<?=$m['paymentFlag']?>">
					<?=$m['tariffCZE']?>
				</div>
			</td>
		</tr>
	<?php endforeach ?>
</table>

<p><a target="_blank" href="mailto:<?php foreach ($activeMemberMailList as $a)
		echo $a.',' ?>">Send email to all active members</a></p>
