<h2>New password</h2>
<form method="post" id="restartPassword">
	<table>
		<tr>
			<td class="right">
				<label for="email">Your registration email: </label>
			</td>
			<td class="left">
				<input type="email" id="email" name="email" required="required"
				       value="<?php if (isset($_SESSION['username']))
					       echo($_SESSION['username']) ?>"/>
				<br/>
			</td>
		</tr>
		<tr>
			<td class="right">
				<label for="year">Anti-spam - Please enter the last year: </label>
			</td>
			<td class="left">
				<input type="text" id="year" name="year" required="required">
				<br/>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="submit" name="sent" value="Send an email with a request for a new password"/>
			</td>
		</tr>
	</table>
</form>
