<h2>Intro</h2>
<!--<p><a href="http://www.activism.net/cypherpunk/crypto-anarchy.html">Read the manifest. Again. </a></p>-->
<div class="intro">
	<ul>
		<li><?=NAME?> developed primarily for the needs of Paralell polis</li>
		<li><?=NAME?> is an internal payment system for the members of Paper Hub, Institute of Cryptoanarchy and Makers Lab
		</li>
		<!--<li>Source codes will be published on GitHub</li>
		<li>Happy hacking, please reporting</li>-->
		<li>First time here? <a href="<?=ROOT?>/en/registration">Register here!</a></li>
	</ul>
</div>
