<h2>
	<i><?= $user['first_name'] ?> <?= $user['last_name'] ?></i>
</h2>
<h3>
	with the tariff <?= $user['tariffENG'] ?> (<?= $tariff['priceCZK'] ?> Kč/month) in <?= $user['name'] ?>
</h3>

<table class="user">
	<tr class="firstRow">
		<td>Date</td>
		<td>Price in BTC</td>
		<td>Status of the invoice</td>
		<td>Payment</td>
		<td>PDF download</td>
		<!--<td>Fičurkies</td>-->
	</tr>
	<?php foreach ($payments as $p): ?>
		<tr>
			<td>
				<?= date("j. n. Y", strtotime($p['payment_first_date'])) ?>
				až <?= date("j. n. Y", strtotime($p['payment_first_date']."+1 month -1 day")) ?>
			</td>
			<td>
				<?= $p['payed_price_BTC'] * 1000 ?> mBTC
			</td>
			<td>
				<b><?= $p['status'] ?></b>
			</td>
			<td>
				<a href="<?= ROOT ?>/en/PayInvoice/pay/<?= $p['id_payment'] ?>">
					<button>Pay</button>
				</a>
			</td>
			<td>
				<a href="<?= ROOT ?>/en/InvoicePdf/<?= $p['invoice_fakturoid_id'] ?>" target="_blank">
					<button>PDF invoice</button>
				</a>
			</td>
		</tr>
	<?php endforeach ?>
</table>
<p>Contact Paper Hub Manager for the change of tariff.</p>