
<h2>New password</h2>
<form method="POST" name="obnoveni_hesla" action="">
    <table>
        <tr>
            <td class="right">
                <label for="password"> New password (6 chars minimum): </label>
            </td>
            <td class="left">
                <input type="password" name="password" id="password" required autocomplete="new-password">
            </td>
        </tr>
        <tr>
            <td class="right">
                <label for="passwordComfirm">Password confirmation: </label>
            </td>
            <td class="left">
                <input type="password" name="passwordComfirm" id="passwordComfirm" required autocomplete="new-password">
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit" name="sent" onclick="return regformhash(this.form, this.form.password, this.form.passwordComfirm);">Reset password</button>
            </td>
        </tr>
    </table>
</form>
