<h2>New password</h2>
<form method="POST" name="obnoveni_hesla" action="">
	<table>
		<tr>
			<td><label for="password"> New password (6 chars at least): </label></td>
			<td><input type="password" name="password" id="password"/></td>
		</tr>
		<tr>
			<td><label for="passwordComfirm">Password confirmation: </label></td>
			<td><input type="password" name="passwordComfirm" id="passwordComfirm"/></td>
		</tr>
		<tr>
			<td></td>
			<td><input type="submit" value="Reset password" name="sent"
					   onclick="return regformhash(this.form, this.form.password, this.form.passwordComfirm);"/></td>
		</tr>
	</table>
</form>